// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxLZw6nIXSWBZ_I-k6g09IlW0I9slu8tg',
    appId: '1:403242152048:web:b4da712f224c3cb493c4b5',
    messagingSenderId: '403242152048',
    projectId: 'spice-7ac6c',
    authDomain: 'spice-7ac6c.firebaseapp.com',
    storageBucket: 'spice-7ac6c.appspot.com',
    measurementId: 'G-ZR1E4W8ZBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQBvhPoVXMOuvVgtRiN9JxFm9bceNR4hA',
    appId: '1:403242152048:android:b250ace7fde44e1893c4b5',
    messagingSenderId: '403242152048',
    projectId: 'spice-7ac6c',
    storageBucket: 'spice-7ac6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXgYQwbFlgAji-bu_clJHudzhkhMV7dKU',
    appId: '1:403242152048:ios:94cffc3ead0f7cac93c4b5',
    messagingSenderId: '403242152048',
    projectId: 'spice-7ac6c',
    storageBucket: 'spice-7ac6c.appspot.com',
    iosClientId: '403242152048-nnp6ij0o9uvqvvh1ms4mk0qrj6a92e36.apps.googleusercontent.com',
    iosBundleId: 'com.example.spice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXgYQwbFlgAji-bu_clJHudzhkhMV7dKU',
    appId: '1:403242152048:ios:94cffc3ead0f7cac93c4b5',
    messagingSenderId: '403242152048',
    projectId: 'spice-7ac6c',
    storageBucket: 'spice-7ac6c.appspot.com',
    iosClientId: '403242152048-nnp6ij0o9uvqvvh1ms4mk0qrj6a92e36.apps.googleusercontent.com',
    iosBundleId: 'com.example.spice',
  );
}
